- set_fact:
    CA_CLIENT_NAME: "{{ hostvars[item]['ansible_fqdn'] }}"

- set_fact:
    CSR_FNAME: "{{ CA_CLIENT_NAME }}.csr"
    CRT_FNAME: "{{ CA_CLIENT_NAME }}.crt"

- name: Save content of cert sign request of "{{ CA_CLIENT_NAME }}" to CA
  copy:
    content: "{{ hostvars[item]['cert_req_content']['content'] | b64decode }}"
    dest: "{{ SSL_CSR_DIR }}/{{ CSR_FNAME }}"

- name: Sign certificate for "{{ CA_CLIENT_NAME }}"
  openssl_certificate:
    path: "{{ SSL_CRT_DIR }}/{{ CRT_FNAME }}"
    privatekey_path: "{{ SSL_PRV_DIR }}/{{ SSL_PRV_FNAME }}"
    # TODO: change and hide passphrase
    privatekey_passphrase: "{{ SSL_PRV_PWD }}"
    csr_path: "{{ SSL_CSR_DIR }}/{{ CSR_FNAME }}"
    provider: selfsigned

- name: Register content of "{{ CRT_FNAME }}" as an ansible fact
  slurp:
    src: "{{ SSL_CRT_DIR }}/{{ CRT_FNAME }}"
  register: cert_tmp

- set_fact:
    certs: "{{ certs | default({}) | combine( { item : cert_tmp } ) }}"
