---

# TODO:
# 1. Check and install openvpn
# 2. Check and generate private key

# Generate VPN crypto staff
- name: Generate Lumba-Lumba VPN client private key
  openssl_privatekey:
    # TODO: rename?
    path: /etc/openvpn/private.key
    type: RSA
    # TODO: No cipher and passphrase?
    size: 4096
    owner: root
    group: root
    mode: 0600

- name: Generate Lumba-Lumba VPN client CSR (certificate signing request)
  openssl_csr:
    path: /etc/openvpn/cert.csr
    privatekey_path: /etc/openvpn/private.key
    common_name: "{{ ansible_fqdn }}"

- name: Register certificate signing request as a ansible fact
  slurp:
    src: /etc/openvpn/cert.csr
  register: cert_req_content

# TODO: group, owner, permission
- name: Get ta.key from VPN server
  copy: content={{ hostvars[groups['vpn-server'][0]]['ta_key_content']['content'] | b64decode }} dest=/etc/openvpn/ta.key

- name: Get ca.crt from SSL CA
  copy: content={{ hostvars[groups['ca'][0]]['ca_crt_content']['content'] | b64decode }} dest=/etc/openvpn/ca.crt

- name: Get crl.pem from SSL CA
  copy: content={{ hostvars[groups['ca'][0]]['crl_pem_content']['content'] | b64decode }} dest=/etc/openvpn/crl.pem

