---
- hosts: just-installed
  roles:
    - basic-configuration
    - wireguard

- hosts: ca
  roles:
    - ca

- hosts: vpn-server
  roles:
    - vpn-server

- hosts: localhost
  connection: local
  roles:
    - vpn-client
