---
#- hosts: just-installed
  #roles:
    #- basic-configuration
    #- wireguard

- hosts: ca
  roles:
    - ca

- hosts: vpn-server
  roles:
    - vpn-server

- hosts: localhost
  connection: local
  roles:
    - vpn-client

- hosts: ca
  tasks:
    - include_tasks: roles/ca/tasks/sign-certs.yml
      with_items: "{{ groups['vpn-client'] }}"

- hosts: vpn-client
  connection: local
  tasks:
    - copy:
        content: "{{ hostvars[groups['ca'][0]]['certs'][inventory_hostname]['content'] | b64decode }}"
        dest: /etc/openvpn/cert.crt

